# Generated by Django 5.2.3 on 2025-06-22 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pallet",
            name="warehouse_object",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pallet",
                to="warehouse.warehouseobject",
            ),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="product_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pallets",
                to="warehouse.productinstance",
            ),
        ),
    ]
