name: Build and deploy Python app with Flutter frontend to Azure Web App - takhzin-hackathon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'  # Set your desired version
          channel: 'stable'

      - name: Create Python virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Python dependencies
        run: pip install -r backend/requirements.txt

      - name: Build Flutter web app
        working-directory: ./frontend
        run: flutter build web

      - name: Copy Flutter build output to Django static directory
        run: |
          mkdir -p backend/static/frontend
          cp -r frontend/build/web/* backend/static/frontend/

      - name: Zip deployment package
        run: |
          zip release.zip ./* -r -x "venv/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7AAC7DC895674874B56155863CD8B7CB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C7CF2820F17D406FB997A25D77E6FF29 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9EB1F709B754489CA109A0286AF5B385 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'takhzin-hackathon'
          slot-name: 'Production'
